### ISSUE TITLE
Photo point bug

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#765] opened 2016-08-16 00:27 UTC
When you accidentally enter in the wrong data/photo and you click remove, it only deletes the photo and not the information/metadata for that photo.

**Comment by chrisala** [comment] 2017-01-06 00:35
Hi Mitch, I can't reproduce this issue - can you please give me some steps to reproduce it?

**Comment by chrisala** [comment] 2017-01-15 22:32
Closing as can't reproduce for now.

**Closed by chrisala** 2017-01-15 22:32 UTC
Labels: bug
