### ISSUE TITLE
Missing activity attachments 

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/fieldcapture#838] opened 2016-10-06 00:04 UTC
Issue raised by Mitch on 6th October 2016
Hi ALA,
 
Can you please look into this project and see if you can retrieve some lost documents?
https://fieldcapture.ala.org.au/admin/auditMessageDetails/57b3a9f1e4b002f8c03497e6?compareId=57b3a9f1e4b002f8c03497e5&searchTerm=Fairlight+Landcare+Group+Hughenden+-+Rubber+Vine+Control+in+Fairlight+Catchment&returnTo=%2Fadmin%2FauditProject%2F8c113424-8711-4ecf-bfb9-1765a1639af4%3FsearchTerm%3DFairlight%2BLandcare%2BGroup%2BHughenden%2B-%2BRubber%2BVine%2BControl%2Bin%2BFairlight%2BCatchment I can see that these 5 docs were attached on the 17th of August, but can’t see any evidence of them being deleted. Seems to be the same as the other issues we had with 25ALG projects around this time.

Initial Analysis:
Forwarded the attachment to Mitch.

Documents are active in the system. It appears it's not been loaded in the activity form

Log info:
eeae1795-4a46-4b40-8386-f99785d7ecc6 > SupportingDocs3 > Report_Delbessie.docx
1a07586a-ee76-4275-ab7c-6a12dc388b0a > additionalinfo2 > Report_Torver Valley.docx
75d7244f-70e4-4ae8-a4b1-c53244f46c38 > supportingDocs2 > Report_Ormonde.docx
c87bbdb5-27f7-4d8c-ac92-f3703617a24e > additionalinfo1 > Report_Fairlight.docx
d658d1a8-d5de-40d9-b1ff-40a88790b966 > supportingDocs1 > Report_Boonderoo.docx

**Comment by chrisala** [comment] 2016-10-19 22:14
duplicate of #787

**Closed by chrisala** 2016-10-19 22:14 UTC
Labels: bug
