### ISSUE TITLE
Add function to download previous reports ESP

### ISSUE THREAD

**Issue by MadeleineDoEE** [AtlasOfLivingAustralia/fieldcapture#1942] opened 2019-11-05 23:32 UTC
Add function for ESP users to download their own reports (without going to Grant Manager view), one year at a time. Need to discuss/decide user interface.

**Comment by chrisala** [comment] 2019-11-14 01:56
Closed as a duplicate of #1924

**Closed by chrisala** 2019-11-14 01:56 UTC
Labels: ESP
